# Generated by Django 4.0.6 on 2022-07-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='imgurl',
            field=models.URLField(blank=True, default='https://ualr.edu/elearning/files/2020/10/No-Photo-Available.jpg', max_length=255),
        ),
    ]
