# Generated by Django 4.0.6 on 2022-07-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='imgurl',
            field=models.URLField(max_length=255),
        ),
    ]
