name: Django Test for Network Project
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        cd 4.Testing_CI_CD
        cd network
        python3 manage.py test